spring:
  application:
    name: zipkin-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
  # 表示当前程序不使用sleuth
  sleuth:
    enabled: false
server:
  port: 9099
# 这个配置没写提示,有点坑,表示zipkin数据存储方式是mysql
zipkin:
  storage:
    type: mysql


